"use client";
import { useState } from "react";
import Link from "next/link";
import useSWR from "swr";
import { DeliveryAPI, isLead, sprintsKey, tasksKey, workspaceKey, type CloseChoice, type Sprint } from "@/API/DeliveryAPI";
export default function SprintsPage({ repoId }: { repoId: string }) {
 const { data: me } = useSWR(workspaceKey, DeliveryAPI.me); const { data: sprints, error, isLoading, mutate } = useSWR(sprintsKey(repoId), () => DeliveryAPI.sprints(repoId)); const { data: tasks, error: tasksError, isLoading: tasksLoading, mutate: mutateTasks } = useSWR(tasksKey(repoId), () => DeliveryAPI.tasks(repoId)); const [name, setName] = useState(""); const [closing, setClosing] = useState<Sprint | null>(null); const [choices, setChoices] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
 async function run(action: () => Promise<unknown>) { setBusy(true); setMessage(""); try { await action(); await Promise.all([mutate(), mutateTasks()]); setClosing(null); } catch (e) { setMessage(e instanceof Error ? e.message : "Action failed. Reload and try again."); } finally { setBusy(false); } }
 const unfinished = tasks?.filter(t => t.sprint_id === closing?.id && t.status !== "done") ?? []; const planned = sprints?.filter(s => s.status === "planned" && s.id !== closing?.id) ?? [];
 return <div className="space-y-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">Sprints</h2><Link href={`/dashboard/repositories/${repoId}/tasks`} className="underline">Tasks</Link></div>{error && <p role="alert">{error.message}</p>}{isLoading && <p>Loading sprints…</p>}{message && <p role="alert">{message}</p>}{isLead(me, repoId) && <form onSubmit={e => { e.preventDefault(); void run(async () => { await DeliveryAPI.createSprint(repoId, name); setName(""); }); }} className="flex gap-2"><input required maxLength={200} aria-label="Sprint name" placeholder="New sprint name" value={name} onChange={e => setName(e.target.value)} className="rounded border bg-transparent p-2" /><button disabled={busy} className="rounded bg-[var(--ws-blue)] text-white px-3">Plan sprint</button></form>}{sprints?.length === 0 && <p>No sprints planned yet.</p>}{sprints?.map(s => <div key={s.id} className="rounded border border-neutral-200 dark:border-neutral-800 p-4"><div className="flex justify-between"><strong>{s.name}</strong><span>{s.status}</span></div><p className="text-sm text-neutral-500">{tasks?.filter(t => t.sprint_id === s.id).length ?? 0} tasks</p>{isLead(me, repoId) && s.status === "planned" && <button disabled={busy} onClick={() => run(() => DeliveryAPI.startSprint(s.id))} className="underline">Start sprint</button>}{isLead(me, repoId) && s.status === "active" && <button disabled={busy || tasksLoading || !!tasksError || !tasks} onClick={() => { setClosing(s); setChoices({}); }} className="underline">Close sprint</button>}</div>)}
 {closing && <div role="dialog" aria-modal="true" aria-label="Close sprint" className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="w-full max-w-xl max-h-[80vh] overflow-auto rounded-lg bg-white dark:bg-neutral-900 p-5 space-y-4"><h3 className="text-lg font-semibold">Close {closing.name}</h3><p>Choose where every unfinished task goes. Completed tasks stay in this sprint.</p>{tasksLoading && <p>Loading tasks…</p>}{tasksError && <p role="alert">Could not load tasks: {tasksError.message}</p>}{tasks && unfinished.map(t => <label key={t.id} className="block"><span>{t.title}</span><select aria-label={`Destination for ${t.title}`} value={choices[t.id] ?? ""} onChange={e => setChoices({ ...choices, [t.id]: e.target.value })} className="block w-full rounded border bg-transparent p-2"><option value="">Choose destination</option><option value="backlog">Backlog</option>{planned.map(s => <option key={s.id} value={s.id}>Carry over to {s.name}</option>)}</select></label>)}{tasks && unfinished.length === 0 && <p>All tasks are done.</p>}<div className="flex gap-2"><button disabled={busy || tasksLoading || !!tasksError || !tasks || unfinished.some(t => !choices[t.id])} onClick={() => run(() => DeliveryAPI.closeSprint(closing.id, unfinished.map(t => choices[t.id] === "backlog" ? { taskId: t.id, action: "backlog" } : { taskId: t.id, action: "carryover", sprintId: choices[t.id] }) as CloseChoice[]))} className="rounded bg-[var(--ws-blue)] text-white px-3 py-2">Close sprint</button><button onClick={() => setClosing(null)} className="rounded border px-3 py-2">Cancel</button></div></div></div>}</div>;
}
