"use client";
import { useState } from "react";
import Link from "next/link";
import useSWR from "swr";
import { DeliveryAPI, isLead, ownsRepo, sprintsKey, tasksKey, workspaceKey, type TaskCategory, type TaskStatus } from "@/API/DeliveryAPI";
import { TeamsAPI, teamByRepoKey } from "@/API/TeamsAPI";
import { ApiError } from "@/API/apiClient";
const statuses: TaskStatus[] = ["backlog", "todo", "in_progress", "in_review", "done"];
export default function TasksPage({ repoId }: { repoId: string }) {
  const { data: me } = useSWR(workspaceKey, DeliveryAPI.me);
  const { data: tasks, error, isLoading, mutate } = useSWR(tasksKey(repoId), () => DeliveryAPI.tasks(repoId));
  const { data: sprints } = useSWR(sprintsKey(repoId), () => DeliveryAPI.sprints(repoId));
  const { data: members } = useSWR(teamByRepoKey(repoId), () => TeamsAPI.findByRepoId(repoId));
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState<TaskCategory>("general"); const [sprintId, setSprintId] = useState(""); const [assigneeId, setAssigneeId] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [assigneeFilter, setAssigneeFilter] = useState("all"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const lead = isLead(me, repoId);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { await DeliveryAPI.createTask({ repoId, title, description, category, ...(sprintId ? { sprintId } : {}), ...(lead && assigneeId ? { assigneeId } : {}) }); setTitle(""); setDescription(""); setSprintId(""); setAssigneeId(""); await mutate(); } catch (e) { setMessage(e instanceof ApiError ? e.message : "Could not create task"); } finally { setBusy(false); } }
  const filtered = tasks?.filter(t => (statusFilter === "all" || t.status === statusFilter) && (assigneeFilter === "all" || (assigneeFilter === "unassigned" ? !t.assignee_id : t.assignee_id === assigneeFilter)));
  return <div className="space-y-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Tasks</h2><Link href={`/dashboard/repositories/${repoId}/sprints`} className="underline">Sprints</Link></div>
    {error && <p role="alert">{error.message}</p>}{isLoading && <p>Loading tasks…</p>}
    {ownsRepo(me, repoId) && <form onSubmit={create} className="rounded-lg border border-neutral-200 dark:border-neutral-800 p-4 space-y-3"><h3 className="font-semibold">Create task</h3><input required maxLength={300} value={title} onChange={e => setTitle(e.target.value)} placeholder="Task title" aria-label="Task title" className="w-full rounded border bg-transparent p-2" /><textarea maxLength={20000} value={description} onChange={e => setDescription(e.target.value)} placeholder="Description" aria-label="Description" className="w-full rounded border bg-transparent p-2" /><div className="flex flex-wrap gap-2"><select value={category} onChange={e => setCategory(e.target.value as TaskCategory)} aria-label="Category" className="rounded border bg-transparent p-2"><option value="general">General</option><option value="developer">Developer</option><option value="designer">Designer</option></select><select value={sprintId} onChange={e => setSprintId(e.target.value)} aria-label="Sprint" className="rounded border bg-transparent p-2"><option value="">Backlog</option>{sprints?.filter(s => s.status !== "closed").map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{lead && <select value={assigneeId} onChange={e => setAssigneeId(e.target.value)} aria-label="Assignee" className="rounded border bg-transparent p-2"><option value="">Unassigned</option>{members?.map(m => <option key={m.user.id} value={m.user.id}>{m.user.username}</option>)}</select>}<button disabled={busy} className="rounded bg-[var(--ws-blue)] text-white px-3 py-2">Create task</button></div></form>}
    {message && <p role="alert">{message}</p>}<div className="flex gap-2"><select aria-label="Filter status" value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="rounded border bg-transparent p-2"><option value="all">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><select aria-label="Filter assignee" value={assigneeFilter} onChange={e => setAssigneeFilter(e.target.value)} className="rounded border bg-transparent p-2"><option value="all">All assignees</option><option value="unassigned">Unassigned</option>{members?.map(m => <option key={m.user.id} value={m.user.id}>{m.user.username}</option>)}</select></div>
    {filtered?.length === 0 && <p>No tasks match this view.</p>}{filtered?.map(t => <Link key={t.id} href={`/dashboard/repositories/${repoId}/tasks/${t.id}`} className="block rounded-lg border border-neutral-200 dark:border-neutral-800 p-3 hover:border-[var(--ws-blue)]"><strong>{t.title}</strong><p className="text-sm text-neutral-500">{t.status.replaceAll("_", " ")} · {t.category} · {members?.find(m => m.user.id === t.assignee_id)?.user.username ?? "Unassigned"} · {sprints?.find(s => s.id === t.sprint_id)?.name ?? "Backlog"}</p></Link>)}</div>;
}
