"use client";
import { useState } from "react";
import Link from "next/link";
import useSWR from "swr";
import { ApiError } from "@/API/apiClient";
import { DeliveryAPI, isLead, ownsRepo, sprintsKey, taskKey, workspaceKey, type TaskCategory, type TaskStatus } from "@/API/DeliveryAPI";
import { TeamsAPI, teamByRepoKey } from "@/API/TeamsAPI";
import { PullRequestsAPI, pullRequestsKey } from "@/API/PullRequestsAPI";
const next: Record<TaskStatus, TaskStatus[]> = { backlog: ["todo"], todo: ["in_progress"], in_progress: ["in_review"], in_review: ["done", "in_progress"], done: ["todo"] };
export default function TaskDetail({ repoId, taskId }: { repoId: string; taskId: string }) {
  const { data: me } = useSWR(workspaceKey, DeliveryAPI.me); const { data: task, error, isLoading, mutate } = useSWR(taskKey(taskId), () => DeliveryAPI.task(taskId)); const { data: sprints } = useSWR(sprintsKey(repoId), () => DeliveryAPI.sprints(repoId)); const { data: members } = useSWR(teamByRepoKey(repoId), () => TeamsAPI.findByRepoId(repoId)); const { data: prs } = useSWR(pullRequestsKey(repoId), () => PullRequestsAPI.findByRepoId(repoId));
  const [title, setTitle] = useState<string | null>(null); const [description, setDescription] = useState<string | null>(null); const [category, setCategory] = useState<TaskCategory | null>(null); const [sprintId, setSprintId] = useState<string | null>(null); const [assigneeId, setAssigneeId] = useState<string | null>(null); const [reopenSprint, setReopenSprint] = useState(""); const [comment, setComment] = useState(""); const [prId, setPrId] = useState(""); const [message, setMessage] = useState(""); const [conflict, setConflict] = useState(false); const [busy, setBusy] = useState(false);
  const owner = ownsRepo(me, repoId), lead = isLead(me, repoId);
  async function run(action: () => Promise<unknown>) { setBusy(true); setMessage(""); setConflict(false); try { await action(); await mutate(); } catch (e) { if (e instanceof ApiError && e.status === 409) { setConflict(true); setMessage("This task changed. Reload it before trying again."); } else setMessage(e instanceof Error ? e.message : "Action failed"); } finally { setBusy(false); } }
  async function reload() { await mutate(); setTitle(null); setDescription(null); setCategory(null); setSprintId(null); setAssigneeId(null); setConflict(false); setMessage(""); }
  if (isLoading) return <p>Loading task…</p>; if (error) return <p role="alert">{error.message}</p>; if (!task) return <p>Task not found.</p>; if (task.repo_id !== repoId) return <p role="alert">This task does not belong to this repository.</p>;
  const allowed = next[task.status].filter(s => lead || (s !== "done" && !(task.status === "in_review" || task.status === "done")));
  return <div className="space-y-5"><Link href={`/dashboard/repositories/${repoId}/tasks`} className="underline">← Tasks</Link><h2 className="text-xl font-semibold">{task.title}</h2><p className="text-sm text-neutral-500">{task.status.replaceAll("_", " ")} · {task.category} · {members?.find(m => m.user.id === task.assignee_id)?.user.username ?? "Unassigned"}</p>{message && <p role="alert">{message} {conflict && <button onClick={reload} className="underline">Reload task</button>}</p>}
    {owner ? <form onSubmit={e => { e.preventDefault(); void run(async () => { await DeliveryAPI.editTask(taskId, { version: task.version, title: title ?? task.title, description: description ?? task.description, category: category ?? task.category, sprintId: (sprintId ?? task.sprint_id) || null, ...(lead ? { assigneeId: (assigneeId ?? task.assignee_id) || null } : {}) }); setTitle(null); setDescription(null); setCategory(null); setSprintId(null); setAssigneeId(null); }); }} className="space-y-2 rounded-lg border border-neutral-200 dark:border-neutral-800 p-4"><h3 className="font-semibold">Edit task</h3><input aria-label="Title" required maxLength={300} value={title ?? task.title} onChange={e => setTitle(e.target.value)} className="w-full rounded border bg-transparent p-2" /><textarea aria-label="Description" maxLength={20000} value={description ?? task.description ?? ""} onChange={e => setDescription(e.target.value)} className="w-full rounded border bg-transparent p-2" /><div className="flex flex-wrap gap-2"><select aria-label="Category" value={category ?? task.category} onChange={e => setCategory(e.target.value as TaskCategory)} className="rounded border bg-transparent p-2"><option value="general">General</option><option value="developer">Developer</option><option value="designer">Designer</option></select><select aria-label="Sprint" value={sprintId ?? task.sprint_id ?? ""} onChange={e => setSprintId(e.target.value)} className="rounded border bg-transparent p-2"><option value="">No sprint</option>{sprints?.filter(s => s.status !== "closed" || s.id === task.sprint_id).map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select>{lead && <select aria-label="Assignee" value={assigneeId ?? task.assignee_id ?? ""} onChange={e => setAssigneeId(e.target.value)} className="rounded border bg-transparent p-2"><option value="">Unassigned</option>{members?.map(m => <option key={m.user.id} value={m.user.id}>{m.user.username}</option>)}</select>}<button disabled={busy || conflict} className="rounded bg-[var(--ws-blue)] text-white px-3 py-2">Save</button></div></form> : <p>{task.description || "No description"}</p>}
    {owner && <section className="space-y-2"><h3 className="font-semibold">Move status</h3><div className="flex gap-2">{task.status === "done" && <label className="text-sm">Target sprint for reopening<select aria-label="Target sprint for reopening" value={reopenSprint} onChange={e => setReopenSprint(e.target.value)} className="ml-2 rounded border bg-transparent p-2"><option value="">Select a sprint</option>{sprints?.filter(s => s.status !== "closed").map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{allowed.map(status => <button key={status} disabled={busy || conflict || (task.status === "backlog" && !task.sprint_id) || (task.status === "done" && (!reopenSprint || !sprints?.some(s => s.id === reopenSprint && s.status !== "closed")))} onClick={() => run(() => DeliveryAPI.editTask(taskId, { version: task.version, status, ...(task.status === "done" ? { sprintId: reopenSprint } : {}) }))} className="rounded border px-3 py-2">{status === "done" ? "Approve" : status === "in_progress" && task.status === "in_review" ? "Request changes" : status === "in_review" ? "Request review" : `Move to ${status.replaceAll("_", " ")}`}</button>)}</div>{task.status === "backlog" && !task.sprint_id && <p className="text-sm">Choose a sprint and save before moving to To do.</p>}{task.status === "done" && <p className="text-sm">Select a non-closed sprint before reopening; the sprint and To do status are saved together.</p>}</section>}
    <section className="space-y-2"><h3 className="font-semibold">Pull requests</h3>{task.links.length === 0 && <p>No linked pull requests.</p>}{task.links.map(link => { const pr = prs?.find(p => p.id === link.pr_id); return <div key={link.pr_id} className="flex gap-2"><a href={pr?.github_url || "#"} className="underline">{pr ? `#${pr.github_pr_number} ${pr.title}` : link.pr_id}</a>{owner && <button disabled={busy} onClick={() => run(() => DeliveryAPI.unlink(taskId, link.pr_id))} className="underline">Unlink</button>}</div>; })}{owner && <div className="flex gap-2"><select aria-label="Pull request" value={prId} onChange={e => setPrId(e.target.value)} className="rounded border bg-transparent p-2"><option value="">Choose same repository PR</option>{prs?.filter(p => !task.links.some(l => l.pr_id === p.id)).map(p => <option value={p.id} key={p.id}>#{p.github_pr_number} {p.title}</option>)}</select><button disabled={!prId || busy} onClick={() => run(async () => { await DeliveryAPI.link(taskId, prId); setPrId(""); })} className="rounded border px-3">Link</button></div>}</section>
    <section className="space-y-2"><h3 className="font-semibold">Comments</h3>{task.comments.length === 0 && <p>No comments yet.</p>}{task.comments.map(c => <div key={c.id} className="rounded border border-neutral-200 dark:border-neutral-800 p-3"><small>{members?.find(m => m.user.id === c.author_id)?.user.username ?? "Member"}</small><p className="whitespace-pre-wrap">{c.body}</p></div>)}{owner && <form onSubmit={e => { e.preventDefault(); void run(async () => { await DeliveryAPI.comment(taskId, comment); setComment(""); }); }} className="space-y-2"><textarea required maxLength={10000} aria-label="Comment" value={comment} onChange={e => setComment(e.target.value)} className="w-full rounded border bg-transparent p-2" /><button disabled={busy} className="rounded border px-3 py-2">Add comment</button></form>}</section></div>;
}
