"use client";
import { useState } from "react";
import Link from "next/link";
import useSWR from "swr";
import { RepositoriesAPI, repositoriesKey } from "@/API/RepositoriesAPI";
import { TeamsAPI, teamByRepoKey } from "@/API/TeamsAPI";
import { OrganizationMembersAPI, orgMembersKey } from "@/API/OrganizationMembersAPI";
import { RepoFollowersAPI, myFollowsKey } from "@/API/RepoFollowersAPI";
import { DeliveryAPI, workspaceKey, type TeamRole } from "@/API/DeliveryAPI";
import FollowControls from "./FollowControls";
import ReviewSuggestionsToggle from "./ReviewSuggestionsToggle";
export default function TeamsContent() {
 const { data: me, error: meError } = useSWR(workspaceKey, DeliveryAPI.me); const { data: repos, error: repoError } = useSWR(repositoriesKey, RepositoriesAPI.findAll); const { data: people } = useSWR(orgMembersKey, OrganizationMembersAPI.findAllWithUserInfo); const { data: follows, mutate: mutateFollows } = useSWR(myFollowsKey, RepoFollowersAPI.findMine); const [repoId, setRepoId] = useState(""); const [userId, setUserId] = useState(""); const [role, setRole] = useState<TeamRole | "remove">("developer"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
 const selectedRepo = repoId || me?.team?.repoId || ""; const { data: roster, mutate: mutateRoster } = useSWR(selectedRepo ? teamByRepoKey(selectedRepo) : null, () => TeamsAPI.findByRepoId(selectedRepo)); const admin = me?.active && me.organizationRole === "admin"; const lead = me?.active && me.team?.repoId === selectedRepo && (me.team.role === "tech_lead" || me.team.role === "project_manager"); const canManage = admin || lead; const chosenMember = roster?.find(m => m.user.id === userId); const canChange = canManage && (admin || !chosenMember || !["tech_lead", "project_manager"].includes(chosenMember.role ?? ""));
 async function assign(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); try { await DeliveryAPI.assignMember(selectedRepo, userId, role === "remove" ? null : role); await mutateRoster(); setMessage("Team assignment updated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Assignment failed"); } finally { setBusy(false); } }
 return <div className="space-y-6"><div><h1 className="text-xl font-semibold">My team</h1><p className="text-neutral-500">Team assignments are managed by leads and administrators. You can follow other repositories for updates.</p></div>{meError && <p role="alert">{meError.message}</p>}{repoError && <p role="alert">{repoError.message}</p>}{!me && !meError && <p>Loading workspace…</p>}{me && !me.team && <p>Ask a team lead to assign you to a repository team.</p>}{me?.team && <div className="rounded border border-neutral-200 dark:border-neutral-800 p-4"><strong>{repos?.find(r => r.id === me.team?.repoId)?.name ?? "Your repository"}</strong><p>Your role: {me.team.role.replaceAll("_", " ")}</p><Link className="underline" href={`/dashboard/repositories/${me.team.repoId}/tasks`}>View team tasks</Link></div>}<ReviewSuggestionsToggle />
 {canManage && <form onSubmit={assign} className="space-y-3 rounded border border-neutral-200 dark:border-neutral-800 p-4"><h2 className="font-semibold">Manage team members</h2><div className="flex flex-wrap gap-2"><select required aria-label="Repository" value={selectedRepo} onChange={e => { setRepoId(e.target.value); setUserId(""); }} className="rounded border bg-transparent p-2">{admin && <option value="">Select repository</option>}{(admin ? repos : repos?.filter(r => r.id === me?.team?.repoId))?.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><select required aria-label="Member" value={userId} onChange={e => setUserId(e.target.value)} className="rounded border bg-transparent p-2"><option value="">Select member</option>{people?.map(p => <option key={p.user.id} value={p.user.id}>{p.user.username}</option>)}</select><select aria-label="Team role" value={role} onChange={e => setRole(e.target.value as TeamRole | "remove")} className="rounded border bg-transparent p-2"><option value="developer">Developer</option><option value="designer">Designer</option>{admin && <><option value="tech_lead">Tech lead</option><option value="project_manager">Project manager</option></>}<option value="remove">Remove from team</option></select><button disabled={busy || !selectedRepo || !userId || !canChange} className="rounded bg-[var(--ws-blue)] text-white px-3 py-2">Save assignment</button></div>{!canChange && <p>Only an administrator can change a lead or project manager.</p>}{roster && <p className="text-sm text-neutral-500">Current team: {roster.map(m => m.user.username).join(", ") || "No members"}</p>}</form>}{message && <p role="alert">{message}</p>}
 <section className="space-y-2"><h2 className="font-semibold">Repositories to follow</h2>{repos?.length === 0 && <p>No repositories yet.</p>}{repos?.map(repo => <div className="flex items-center justify-between gap-3 border-b border-neutral-200 dark:border-neutral-800 py-3" key={repo.id}><Link href={`/dashboard/repositories/${repo.id}/code`} className="underline">{repo.name}</Link><FollowControls repoId={repo.id} follow={follows?.find(f => f.repo_id === repo.id) ?? null} onChanged={mutateFollows} /></div>)}</section></div>;
}
